### ISSUE TITLE
	Cannot read property 'access_key' of undefined

### ISSUE THREAD

**Issue by SoerenKaiser99** [mameier1234/ioBroker.blueconnect#15]
**To Reproduce**  
on every start of the adapter

**Expected behavior**  
no mesurements are possible - problem with acces_key

**Screenshots & Logfiles**  

blueconnect.0 | 2022-05-12 23:02:07.129 | error | Cannot read property 'access_key' of undefined
-- | -- | -- | --
blueconnect.0 | 2022-05-12 23:02:07.128 | error | TypeError: Cannot read property 'access_key' of undefined at Request._callback (/opt/iobroker/node_modules/iobroker.blueconnect/main.js:332:47) at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22) at Request.emit (events.js:400:28) at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10) at Request.emit (events.js:400:28) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12) at Object.onceWrapper (events.js:519:28) at IncomingMessage.emit (events.js:412:35) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)
blueconnect.0 | 2022-05-12 23:02:07.127 | error | uncaught exception: Cannot read property 'access_key' of undefined
blueconnect.0 | 2022-05-12 23:02:01.668 | info | starting. Version 0.0.1 in /opt/iobroker/node_modules/iobroker.blueconnect, 

node: v14.19.2, js-controller: 4.0.23

**Comment by kopierschnitte** [comment]
It looks like an authentication problem as the blueriiot server doesn't send a token back to you. Unfortunately, that's currently not being handled by the adapter.
Could you please double check your credentials? Are there any special characters (symbols, spaces) in it?

**Comment by kopierschnitte** [comment]
... or you could try using my fork for the moment. Please continue here: https://github.com/mameier1234/ioBroker.blueconnect/issues/16#issuecomment-1165787975

**Comment by SoerenKaiser99** [comment]
Hi, sorry i was on holidays this we.
Credentials are fine, the app run`s without problems.

I will try the the fork in a few minutes and let u know what happens.
br 
Sören

PS:oder lieber auf deutsch? ;)

**Comment by kopierschnitte** [comment]
Gerne ;-)

Ich hoffe, es klappt. Kann mir den Fehler sonst schwer erklären. Problem ist, es gibt nix Offizielles und alles ist durch Ausprobieren erstellt worden.

Die MQTT-Variante ist stark auf ein anderes Smarthome-System ausgelegt und sehr fummelig zu installieren (Docker).

**Comment by SoerenKaiser99** [comment]
@kopierschnitte your fork works perfekt for me too! :) Thanks!
would you ask dutchman to assist you to get it in the repo?

**Comment by SoerenKaiser99** [comment]
> Gerne ;-)
> 
> Ich hoffe, es klappt. Kann mir den Fehler sonst schwer erklären. Problem ist, es gibt nix Offizielles und alles ist durch Ausprobieren erstellt worden.
> 
> Die MQTT-Variante ist stark auf ein anderes Smarthome-System ausgelegt und sehr fummelig zu installieren (Docker).

Läuft Prima :) Du solltest dich mal an Dutch wenden damit dein Fork ins repo kommt da ja alle das Problem haben(werden).

Hast du eine Idee ob man den Wert wake_period im Hauptverzeichnis auch schreiben kann?

**Comment by kopierschnitte** [comment]
Cool.
Der Adapter ist leider noch weit vom Release entfernt... gebe mir aber Mühe.
Schreiben kannst Du leider noch nix. Das akzeptiert die Schnittstelle von denen noch nicht wirklich :-(
