### ISSUE TITLE
instance system.adapter.blueconnect.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

### ISSUE THREAD

**Issue by phifogg** [mameier1234/ioBroker.blueconnect#16]
**Describe the bug**  
The adapter worked fine last year. During winter I put the blue into sleep mode. After waking up this year, the adapter doesn't work anymore. Evertime the scheduler starts i failed with code 6.

**To Reproduce**  
every schedule run ends with code 6

**Expected behavior**  

**Screenshots & Logfiles**  

host.volantis.draes.net | 2022-06-08 11:49:02.908 | error | instance system.adapter.blueconnect.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
xxxx| 2022-06-08 11:49:00.095 | info | instance system.adapter.blueconnect.0 started with pid 4733
xxxx | 2022-06-08 11:48:05.295 | info | instance scheduled system.adapter.blueconnect.0 */1 * * * *

**Versions:**  
 - Adapter version: 0.0.1
 - JS-Controller version: 4.0.23
 - Node version: 14.8.3
 - Operating system: OSX High Sierra

**Additional context**

**Comment by Stonelink77** [comment]
Same here, Adapter worked perfect last Year till araound october, then sleep mode for the blue connect. System used ist ioBroker with a raspberry Pi4 Buster JS-Controller 4.0.23 Node js Version 16.15.1 NPM 8.11.0

Now I also get this error 6 message and 2 other messages:
instance system.adapter.blueconnect.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

Cannot read properties of undefined (reading 'access_key')

TypeError: Cannot read properties of undefined (reading 'access_key') at Request._callback (/opt/iobroker/node_modules/iobroker.blueconnect/main.js:332:47) at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22) at Request.emit (node:events:527:28) at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10) at Request.emit (node:events:527:28) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12) at Object.onceWrapper (node:events:641:28) at IncomingMessage.emit (node:events:539:35) at endReadableNT (node:internal/streams/readable:1345:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)



any ideas how to fix the problem? Seems to have to do with the key...? as mentioned it was all working fine last year... 

thx and kind regards...

**Comment by kopierschnitte** [comment]
That's strange, indeed. I remember that Blueriiot changed the requirements for the requests some time ago.
Maybe you could try my fork (https://github.com/kopierschnitte/ioBroker.blueconnect) because it's working perfectly for me at the moment.

I hadn't time to maintain or create a pull request but in the meantime, it's worth a try ;-)

**Comment by Stonelink77** [comment]
Hey, thx for your fast reply. And yes I will give it a try… hope to get along with all this since I’m not a pro 😉.

There also seems to be a Mqtt solution out there… 

I’ll give u a feedback!

Ciao ✋

**Comment by phifogg** [comment]
I installed your fork @kopierschnitte, this works just fine. Thanks! Any idea what could be the culprit?

**Comment by kopierschnitte** [comment]
Not sure but I guess the vendor has fine tuned the inspection of the requests in order to make sure that only the App connects to their service ;-)
